### PR TITLE
Upload Syllabus to the Postgres Database

### PR DESCRIPTION
**Pull request by Philewj**
Restore Pull

### CODE REVIEW

**Review by davjenni7 — CHANGES_REQUESTED** [review]
AttributeError: module 'catalogue.views' has no attribute 'add_feedback'

**Review by Philewj — COMMENTED** [review]
Try this

**Review by davjenni7 — CHANGES_REQUESTED** [review]
New error

AttributeError: module 'catalogue.views' has no attribute 'upload_Syllabus'. Did you mean: 'uploadSyllabus'?

**Review by davjenni7 — APPROVED** [review]
Works. Just FYI, none of the new pages can be accessed

**Pull request merged**
